### ISSUE TITLE
FORCE INDEX failure

### ISSUE THREAD

**Issue by witchi** [greenlion/PHP-SQL-Parser#125]
_From [bramanin...@gmail.com](https://code.google.com/u/102036476916452246881/) on October 27, 2013 10:26:53_

What steps will reproduce the problem? 1. 2. 3. What is the expected output? What do you see instead? case:
SELECT ... FROM tbl FORCE INDEX (col1_idx) WHERE ... ORDER BY col1
output:
SELECT ... FROM tbl WHERE ... ORDER BY col1,
it removes FORCE INDEX... and 
PHP produce notice:
A PHP Error was encountered
Severity: Notice
Message: Undefined variable: token_category
Filename: PHP-SQL-Parser/php-sql-parser.php
Line Number: 912 What version of the product are you using? On what operating system? PHP 5.4 x64, WIN 7 Please provide any additional information below.

_Original issue: http://code.google.com/p/php-sql-parser/issues/detail?id=99_

**Comment by witchi** [comment]
_From [pho...@gmx.de](https://code.google.com/u/109317404671582518013/) on November 01, 2013 08:57:24_

At the moment the parser doesn't recognize index hints, Don't use it. http://dev.mysql.com/doc/refman/5.0/en/index-hints.html

**Status:** Accepted  
  **Owner:** pho...@gmx.de

**Comment by witchi** [comment]
_From [pho...@gmx.de](https://code.google.com/u/109317404671582518013/) on April 02, 2014 07:26:18_

I have added some code to handle index hints, but it will be part of further enhancements.

**Status:** Started

**Comment by witchi** [comment]
_From [pho...@gmx.de](https://code.google.com/u/109317404671582518013/) on September 15, 2014 03:43:15_

Issue 140 has been merged into this issue.

**Comment by czoIg** [comment]
Index hints for FROM part is already working, but I've added hints for JOINs in PR #359.
