### ISSUE TITLE
Argument by reference  is deprecated

### ISSUE THREAD

**Issue by adrianoac** [greenlion/PHP-SQL-Parser#189]
Your contribution is very good and It works great.

Pass the argument by reference  is deprecated, in php version 5.3 is warning, in php version 5.4 is fatal error.  More information in http://php.net/manual/en/language.references.pass.php

This may affect the use of sql parse?

**Comment by witchi** [comment]
Ooops, this will break the parser.

**Comment by witchi** [comment]
I have searched through the code for "&$", but the only places I have found, are the function declarations. So it seems there are no function calls with explicit pas-by-references. The exceptions occur only on

$x = foo(&$x);

So the parser should work as expected.

**Comment by witchi** [comment]
Currently I use 5.6.1 in the Eclipse IDE, and such an exception has never been occurred.

**Comment by adrianoac** [comment]
OK, I tested the php version 5.5 and there were no problems as well. I'm sorry if I caused any confusion. And thank you for your attention. I use the library for my studies and she is very good.

Thanks for the input.
