### ISSUE TITLE
add new option for issue specific behavior

### ISSUE THREAD

**Issue by greenlion** [greenlion/PHP-SQL-Parser#207]
from https://github.com/greenlion/PHP-SQL-Parser/pull/206
> And from on high it was heard the Maintainer say:
> I shall then add a new parameter to the constructor, and it shall be called 'options' and it shall be an array and it shall be good.
> 
> If you place the key 'issue_207' into this array, I will modify the output so that all three *_PARAM_PARAMETERS outputs are made into arrays as you request.
> 
> I'll add this sometime soon. I'm busy working on some other stuff right now.

So it must be made so.

**Comment by Rastusik** [comment]
I'm not sure how you meant this, but I'll take a look at it tomorrow :)
