### ISSUE TITLE
Consider Git Flow approach

### ISSUE THREAD

**Issue by polevaultweb** [greenlion/PHP-SQL-Parser#221]
@greenlion would it be possible to have `master` inline with the latest release tag, and feature branches merged into a `develop` branch?

Essentially rename `master` to `develop` and cut a new `master` off `v4.1.0`

**Comment by greenlion** [comment]
Why not just create a new develop branch and merge into master, and tag master?  Just curious.

**Comment by polevaultweb** [comment]
I think we are saying the same thing? 😄 

Essentially master would always be in the same state as the last released tag.

**Comment by greenlion** [comment]
this is done.  I have made a new point release to anchor master to a release, and merged all changes into the older develop branch from master.
