### ISSUE TITLE
Quotes in comments break parser, returns false

### ISSUE THREAD

**Issue by dbould** [greenlion/PHP-SQL-Parser#233]
```
#Check parser doesn't break with single quotes
CREATE TABLE moomoo (cow VARCHAR(20));
```

This will return false.  Removing the ' from doesn't returns an array of parsed SQL as expected.

**Comment by dbould** [comment]
Fixed in PR https://github.com/greenlion/PHP-SQL-Parser/pull/235

**Comment by greenlion** [comment]
Thanks.
