### ISSUE TITLE
Negative integers in IN() get broken

### ISSUE THREAD

**Issue by andreasfernandez** [greenlion/PHP-SQL-Parser#24]
Hello,
we have a query like this: `SELECT * FROM table WHERE id IN(0,-1,-2,-3)`. The SQLParser does not handle this properly, creating the result again with SQLCreator breaks the query: `SELECT * FROM table WHERE id IN(0,-,1,-,2,-,3)`. As far as I could investigate, reason is the "-" splitter in LexerSplitter.php.

**Comment by witchi** [comment]
I have added a test case and have enhanced the Lexer to recognize signs of a number. Your example seems to work.
