### ISSUE TITLE
Repatriate issues from Google Code to GitHub

### ISSUE THREAD

**Issue by tristanleboss** [greenlion/PHP-SQL-Parser#25]
Hello,

Some open issues are still on the Google Code page. Because Google Code will soon be turned off, it may be interesting to repatriate them on GitHub.

Here they are:

https://code.google.com/p/php-sql-parser/issues/list?can=2

Also, at least 2 of them seem to contain fixes:

https://code.google.com/p/php-sql-parser/issues/detail?id=155
https://code.google.com/p/php-sql-parser/issues/detail?id=154

Regards,

Tristan

**Comment by gena01** [comment]
+1

**Comment by witchi** [comment]
I try to add all issues from GoogleCode by https://github.com/arthur-debert/google-code-issues-migrator
There is no way to export the issue attachments, maybe I can move them to GoogleDrive and set new links.
