### ISSUE TITLE
Normalized sub-classes to make compatible with PHP 7.2

### ISSUE THREAD

**Issue by dbalmf** [greenlion/PHP-SQL-Parser#274]
Abstract class processors/AbstractProcessor.php::process() is used in subclasses where its operands are incompatible in php 7.2.

public abstract function process($tokens, $void = '');

is not compatible with subclass in processors/InsertProcessor.php

public function process($tokenList, $token_category = "INSERT")

**Comment by lpotherat** [comment]
Hi, 
Same Here : Declaration of PHPSQLParser\processors\DuplicateProcessor::process($tokens) must be compatible with PHPSQLParser\processors\SetProcessor::process($tokens, $isUpdate = false) in /var/www/wftest/vendor/greenlion/php-sql-parser/src/PHPSQLParser/processors/DuplicateProcessor.php

**Comment by Hoten** [comment]
Saw this when updating PHP (From 7.0 to 7.2).
