### ISSUE TITLE
Error during building parsed sub subquery

### ISSUE THREAD

**Issue by ghost** [greenlion/PHP-SQL-Parser#284]
I am trying to parse this simplified piece of sql query.
`SELECT (SELECT SUM(1) FROM table1 WHERE ((SELECT SUM(2) FROM table2))) FROM table2`
Parsing is successful, but during buiding sql from parsed array it shows this ErrorException:
> unknown [expr_type] = subquery in "WHERE expression subtree" [0]

It seems it cannot be parsed because of double brackets in WHERE clause. Can it be fixed, please? Thank you.

Exception is on the line:

> \src\PHPSQLParser\builders\WhereBracketExpressionBuilder.php:114

**Comment by Quadman4853** [comment]
> 
> 
> Same here, it's failing because of subquery:
> `...LEFT JOIN pd_table AS d ON d.id = (SELECT MAX(id) FROM pd_table WHERE supplierId = c.id AND type = 5)...`
> 
> > Uncaught exception (PHPSQLParser\exceptions\UnableToCreateSQLException): unknown [expr_type] = subquery in "expression ref_clause" [2]
> > in file `/data/project/vendor/greenlion/php-sql-parser/src/PHPSQLParser/builders/RefClauseBuilder.php:45`

I am not sure how I fixed it temporarily any more, but I think when I modified \PHPSQLParser\builders\WhereBracketExpressionBuilder.php => **buildWhereExpression** method like this:
```
    protected function buildWhereExpression($parsed) {
        $builder = new WhereExpressionBuilder();
        return $builder->build($parsed);
    }
```
it may work, give a feedback if you try to resolve this. Thank you.
