### ISSUE TITLE
Update breaks on CENTOS 7 using PHP7

### ISSUE THREAD

**Issue by hellojacknorell** [greenlion/PHP-SQL-Parser#297]
Error message, seems the installed motranslator is too new?

Error: Package: php-phpmyadmin-sql-parser-4.2.5-1.el7.noarch (epel)
           Requires: php-composer(phpmyadmin/motranslator) < 4
           Installed: php-phpmyadmin-motranslator-4.0-1.el7.remi.noarch (@remi)
               php-composer(phpmyadmin/motranslator) = 4.0
           Available: php-phpmyadmin-motranslator-3.4-1.el7.noarch (epel)
               php-composer(phpmyadmin/motranslator) = 3.4

**Comment by infosolve** [comment]
Hi Folks,

Was there a resolution to this problem? I'm having the same issue.

**Comment by shahinIman** [comment]
Hi there,
i solved it the following way
yum remove php-phpmyadmin-sql-parser-4.2.5-1.el7.noarch
yum remove php-phpmyadmin-motranslator-4.0-1.el7.remi.noarch
then
yum install php-phpmyadmin-sql-parser-4.2.5-1.el7.noarch php-phpmyadmin-motranslator-4.0-1.el7.remi.noarch

it worked for me.

**Comment by monojp** [comment]
@hellojacknorell isn't that a packaging issue from centos/remi unrelated to the library and should be closed?

**Comment by hellojacknorell** [comment]
@monojp Don't know, seems odd that the package expects an earlier dependency rather than a later version to me, but no clue as to where that issue has come up.

@shahinIman I resolved this similarly by removing the motranslator version and installing an earlier specific version which sql parser then accepted.

Closing this as solution now available.
