### ISSUE TITLE
Multiplication operator wrongly identified as a "colref"

### ISSUE THREAD

**Issue by nicoder** [greenlion/PHP-SQL-Parser#335]
Hi,

If a multiplication operator is positioned before a function expression its `expr_type` is parsed as `'operator'`:

```php
        $parser = new PHPSQLParser();

        $parser->parse('SELECT 15 * ROUND(3, 1) FROM dual');
        var_dump($parser->parsed['SELECT'][0]['sub_tree'][1]['base_expr']); // string(1) "*"
        var_dump($parser->parsed['SELECT'][0]['sub_tree'][1]['expr_type']); // string(8) "operator"
```

But if it comes after the function expression its `expr_type` is parsed as `'colref'`:

```php
        $parser = new PHPSQLParser();

        $parser->parse('SELECT ROUND(3, 1) * 15 FROM dual');
        var_dump($parser->parsed['SELECT'][0]['sub_tree'][1]['base_expr']); // string(1) "*"
        var_dump($parser->parsed['SELECT'][0]['sub_tree'][1]['expr_type']); // string(8) "colref" <== why?
```

**Comment by greenlion** [comment]
Hmm. Handling * as a colref is for handling:
select * from ...

That can also be select expr1, ..., * from table

I am not sure this fix makes this work properly.  If not I will have to inspect this more thoroughly myself.
