### ISSUE TITLE
PHP 8.1 supporting

### ISSUE THREAD

**Issue by tarasTrujay** [greenlion/PHP-SQL-Parser#347]
Hi guys! 
Have some deprecations on PHP 8.1:

`Deprecated: preg_split(): Passing null to parameter #3 ($limit) of type int is deprecated in /development/application/vendor/greenlion/php-sql-parser/src/PHPSQLParser/lexer/PHPSQLLexer.php on line 87`

`Deprecated: Automatic conversion of false to array is deprecated in /development/application/vendor/greenlion/php-sql-parser/src/PHPSQLParser/processors/SQLProcessor.php on line 506`

and so on. 

Could you fix these?

**Comment by genyslt** [comment]
Any news?

**Comment by garethellis36** [comment]
PR #346 was opened to address the first deprecation, but it hasn't been merged yet. @greenlion Any idea when this might get merged please?

**Comment by greenlion** [comment]
Will look at the PR this weekend and merge.

**Comment by garethellis36** [comment]
Thank you. Would you like a PR for the second deprecation?

**Comment by greenlion** [comment]
Yes, please!

**Comment by greenlion** [comment]
Ok, I'll check it out. I will have to update the test suite.  Will do
this weekend.

**Comment by nicoder** [comment]
hi @greenlion

I had a go at upgrading phpunit and making the test suite pass on php 8.1 without deprecations:
https://github.com/greenlion/PHP-SQL-Parser/pull/350

**Comment by greenlion** [comment]
Thank you everybody for your help.  All three fixes are merged today.

**Comment by garethellis36** [comment]
Thanks! Do you have any plans for when you might tag this as a release?

**Comment by greenlion** [comment]
I can do that later today.

**Comment by greenlion** [comment]
Done.
