### ISSUE TITLE
json syntax err ->>

### ISSUE THREAD

**Issue by mynamevincent** [greenlion/PHP-SQL-Parser#386]
sql: SELECT
                `unId`, `spu`, `data` ->> \'$.finalSampleIdentifyTime\' as `finalSampleIdentifyTime`, `data`->>\'$.editionReviewerAnalysisTime\' AS `editionReviewerAnalysisTime`,
                `cmsPlanningTime`, `sampleMerchandiser`, `data`->>\'$.printingChannel\' AS `printingChannel`, `status`, `isSpecial`    
            FROM
                `am_return_analysis_process`
            WHERE
                 1  AND `data`->>\'$.printingChannel\' = \'1\'  AND ( `sampleMerchandiser` LIKE \'%"linhuijun"%\') AND `status` = \'analystChecked\' AND `status` != \'repealed\'

EXCEPTION : "cannot calculate position of - within  ->> '$.finalSampleIdentifyTime' as `finalSampleIdentifyTime`, `data`->>'$.editionReviewerAnalysisTime' AS `editionReviewerAnalysisTime`,
                `cmsPlanningTime`, `sampleMerchandiser`, `data`->>'$.printingChannel' AS `printingChannel`, `status`, `isSpecial`    
            FROM
                `am_return_analysis_process`
            WHERE
                 1  AND `data`->>'$.printingChannel' = '1'  AND ( `sampleMerchandiser` LIKE '%"linhuijun"%') AND `status` = 'analystChecked' AND `status` != 'repealed'" in /include/composer/vendor/greenlion/php-sql-parser/src/PHPSQLParser/positions/PositionCalculator.php on line 249. Timestamp : 1724641000

**Comment by greenlion** [comment]
The parser is for versions of MySQL that predate JSON support.  You can probably add ->> as an operator with some work.
